os_name                 = "ubuntu"
os_version              = "25.04"
os_arch                 = "aarch64"
iso_url                 = "https://releases.ubuntu.com/plucky/ubuntu-25.04-live-server-arm64.iso"
iso_checksum            = "file:https://releases.ubuntu.com/plucky/SHA256SUMS"
parallels_guest_os_type = "ubuntu"
vbox_guest_os_type      = "Ubuntu24_LTS_arm64"
vmware_guest_os_type    = "arm-ubuntu-64"
utm_vm_icon             = "ubuntu"
boot_command            = ["<wait>e<wait><down><down><down><end> autoinstall ds=nocloud-net\\;s=http://{{.HTTPIP}}:{{.HTTPPort}}/ubuntu/<wait><f10><wait>"]
