os_name                 = "ubuntu"
os_version              = "25.10"
os_arch                 = "x86_64"
iso_url                 = "https://cdimage.ubuntu.com/releases/questing/release/ubuntu-25.10-live-server-amd64.iso"
iso_checksum            = "file:https://cdimage.ubuntu.com/releases/questing/release/SHA256SUMS"
parallels_guest_os_type = "ubuntu"
vbox_guest_os_type      = "Ubuntu_64"
vmware_guest_os_type    = "ubuntu-64"
utm_vm_icon             = "ubuntu"
boot_command            = ["<wait>e<wait><down><down><down><end> autoinstall ds=nocloud-net\\;s=http://{{.HTTPIP}}:{{.HTTPPort}}/ubuntu/<wait><f10><wait>"]
