os_name                 = "almalinux"
os_version              = "9.7"
os_arch                 = "x86_64"
iso_url                 = "https://repo.almalinux.org/almalinux/9/isos/x86_64/AlmaLinux-9.7-x86_64-boot.iso"
iso_checksum            = "file:https://repo.almalinux.org/almalinux/9/isos/x86_64/CHECKSUM"
parallels_guest_os_type = "rhel"
vbox_guest_os_type      = "RedHat_64"
vmware_guest_os_type    = "centos-64"
utm_vm_icon             = "almalinux"
boot_command            = ["<wait><up><wait>e<wait><down><wait><down><wait><end><wait> inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/rhel/ks.cfg inst.repo=https://repo.almalinux.org/almalinux/9/BaseOS/x86_64/os/ <wait><leftCtrlOn><wait>x<wait><leftCtrlOff>"]
