---
on:
  workflow_call:

env:
  PACKER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  aarch64:
    runs-on: [self-hosted, ARM64, qemu]
    strategy:
      fail-fast: false
      matrix:
        os:
          - almalinux-8
          - almalinux-9
          - centos-7
          - centos-stream-8
          - centos-stream-9
          - debian-11
          - debian-12
          - fedora-38
          - fedora-39
          - freebsd-13
          - freebsd-14
          - opensuse-leap-15
          - oracle-7
          - oracle-8
          - oracle-9
          - rockylinux-8
          - rockylinux-9
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-23.10
        provider:
          - qemu
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Vagrant QEMU
        run: |
          brew install qemu libvirt
          brew tap hashicorp/tap
          brew install --cask hashicorp/tap/hashicorp-vagrant
          vagrant plugin install vagrant-libvirt vagrant-qemu
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Install Bento
        run: |
          eval "$(chef shell-init bash)"
          gem build bento.gemspec
          gem install bento-*.gem
      - name: Bento build
        run: |
          rm -rf builds
          sudo mkdir -p /mnt/builds/iso
          sudo chmod -R 777 /mnt/builds
          sudo ln -s /mnt/builds ./
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm --vars "qemu_accelerator=hvf" os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-aarch64.pkrvars.hcl"
          ls -alh builds/
      - name: Bento Test
        run: |
          eval "$(chef shell-init bash)"
          bento test
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.os }}-qemu-aarch64"
          path: |
            builds
            !builds/uploaded/*
          retention-days: 10
