---
on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-lint:
    uses: ./.github/workflows/ci-lint.yml
    secrets: inherit

  pkr-bld-amazonlinux:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-amazonlinux.yml
    secrets: inherit

  pkr-bld-hyperv:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-hyperv.yml
    secrets: inherit

  pkr-bld-parallels:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-parallels.yml
    secrets: inherit

  pkr-bld-qemu:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-qemu.yml
    secrets: inherit

  pkr-bld-utm:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-utm.yml
    secrets: inherit

  pkr-bld-virtualbox:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-virtualbox.yml
    secrets: inherit

  pkr-bld-vmware:
    needs: ci-lint
    uses: ./.github/workflows/pkr-bld-vmware.yml
    secrets: inherit

  check_jobs_pass:
    if: always()
    needs:
      - ci-lint

    runs-on: Ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-failures:
          allowed-skips: ${{ toJSON(needs) }}
          jobs: ${{ toJSON(needs) }}
