---
on:
  push:
    branches:
      - main
  schedule: [cron: "0 0 1 */3 *"]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-x86_64:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - almalinux-8
          - almalinux-9
          - amazonlinux-2
          - centos-7
          - centos-stream-8
          - centos-stream-9
          - debian-10
          - debian-11
          - fedora-36
          - fedora-37
          - freebsd-12
          - freebsd-13
          - opensuse-leap-15
          - oraclelinux-7
          - oraclelinux-8
          - oraclelinux-9
          - rockylinux-8
          - rockylinux-9
          - scientificlinux-7
          - springdalelinux-7
          - springdalelinux-8
          - springdalelinux-9
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-22.10
          - windows-10
          - windows-11
          - windows-2012r2
          - windows-2016
          - windows-2019
          - windows-2022
        provider:
          - qemu
          - virtualbox-iso
    steps:
      - name: Install qemu
        run: brew install qemu
      - name: Checkout
        uses: actions/checkout@main
      - name: Pull Change list
        id: changed-files
        uses: collin-miller/git-changesets@master
      - name: Verify Changed files
        id: verify-changed-files
        run: |
          echo '${{ steps.changed-files.outputs.added_modified }}' > changed.txt
          if grep ".*\.pkrvars.hcl" changed.txt; then
            echo "::set-output name=files_changed::true"
          else
            echo "::set-output name=files_changed::false"
          fi
            - name: Setup Packer
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Packer Init
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          PACKER_GITHUB_API_TOKEN: "${{ secrets.PACKER_GITHUB_API_TOKEN }}"
        run: packer init packer_templates
      - name: Packer build
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: packer build -only=${{ matrix.provider }} -var-file=os_pkrvars/"${{ matrix.os }}-x86_64.pkrvars.hcl" packer_templates
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            builds
            !builds/packer-*/*
            !build/.gitkeep
          retention-days: 10

  build-linux-aarch64:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os:
          - almalinux-8
          - almalinux-9
          - centos-7
          - centos-stream-8
          - centos-stream-9
          - debian-10
          - debian-11
          - fedora-36
          - fedora-37
          - oraclelinux-7
          - oraclelinux-8
          - oraclelinux-9
          - rockylinux-8
          - rockylinux-9
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-22.10
        provider:
          - parallels
          - qemu
          - virtualbox-iso
          - vmware
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Pull Change list
        id: changed-files
        uses: collin-miller/git-changesets@master
      - name: Verify Changed files
        id: verify-changed-files
        run: |
          echo '${{ steps.changed-files.outputs.added_modified }}' > changed.txt
          if grep ".*\.pkrvars.hcl" changed.txt; then
            echo "::set-output name=files_changed::true"
          else
            echo "::set-output name=files_changed::false"
          fi
            - name: Setup Packer
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Packer Init
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          PACKER_GITHUB_API_TOKEN: "${{ secrets.PACKER_GITHUB_API_TOKEN }}"
        run: packer init packer_templates
      - name: Packer build
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: packer build -only=${{ matrix.provider }} -var-file=os_pkrvars/"${{ matrix.os }}-aarch64.pkrvars.hcl" packer_templates
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            builds
            !builds/packer-*/*
            !build/.gitkeep
          retention-days: 10
