---
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  markdown-lint:
    uses: chef/github-workflows/.github/workflows/markdown-lint.yml@main

  markdown-link-checker:
    uses: chef/github-workflows/.github/workflows/markdown-link-checker.yml@main

  yaml-lint:
    uses: chef/github-workflows/.github/workflows/yaml-lint.yml@main

  json-lint:
    uses: chef/github-workflows/.github/workflows/json-lint.yml@main

  xml-lint:
    uses: chef/github-workflows/.github/workflows/xml-lint.yml@main

  shellcheck-lint:
    uses: chef/github-workflows/.github/workflows/shellcheck-lint.yml@main

  powershell-lint:
    uses: chef/github-workflows/.github/workflows/powershell-lint.yml@main

  packer-iso-check:
    uses: chef/github-workflows/.github/workflows/packer-iso-url-checker.yml@main

  packer-lint:
    uses: chef/github-workflows/.github/workflows/packer-lint.yml@main
    secrets: inherit
