---
on:
  pull_request:

jobs:
#  markdown-lint:
#    uses: chef/github-workflows/.github/workflows/markdown-lint.yml@main
#
#  markdown-link-checker:
#    uses: chef/github-workflows/.github/workflows/markdown-link-checker.yml@main
#
#  yaml-lint:
#    uses: chef/github-workflows/.github/workflows/yaml-lint.yml@main
#
#  json-lint:
#    uses: chef/github-workflows/.github/workflows/json-lint.yml@main
#
#  xml-lint:
#    uses: chef/github-workflows/.github/workflows/xml-lint.yml@main
#
#  shellcheck-lint:
#    uses: chef/github-workflows/.github/workflows/shellcheck-lint.yml@main
#
#  powershell-lint:
#    uses: chef/github-workflows/.github/workflows/powershell-lint.yml@main
#
#  packer-iso-check:
#    uses: chef/github-workflows/.github/workflows/packer-iso-url-checker.yml@main
#    secrets: inherit
#
#  packer-lint:
#    uses: chef/github-workflows/.github/workflows/packer-lint.yml@main
#    secrets: inherit

  packer-builds-amzlinux:
#    needs:
#      - yaml-lint
#      - json-lint
#      - xml-lint
#      - powershell-lint
#      - shellcheck-lint
#      - packer-iso-check
#      - packer-lint
    uses: ./.github/workflows/packer-builds-amzlinux.yml
    secrets: inherit

#  packer-builds-hyperv:
#    #    needs:
#    #      - yaml-lint
#    #      - json-lint
#    #      - xml-lint
#    #      - powershell-lint
#    #      - shellcheck-lint
#    #      - packer-iso-check
#    #      - packer-lint
#    uses: ./.github/workflows/packer-builds-hyperv.yml
#    secrets: inherit

  packer-builds-parallels:
    #    needs:
    #      - yaml-lint
    #      - json-lint
    #      - xml-lint
    #      - powershell-lint
    #      - shellcheck-lint
    #      - packer-iso-check
    #      - packer-lint
    uses: ./.github/workflows/packer-builds-parallels.yml
    secrets: inherit

#  packer-builds-qemu:
#    #    needs:
#    #      - yaml-lint
#    #      - json-lint
#    #      - xml-lint
#    #      - powershell-lint
#    #      - shellcheck-lint
#    #      - packer-iso-check
#    #      - packer-lint
#    uses: ./.github/workflows/packer-builds-qemu.yml
#    secrets: inherit

  packer-builds-virtualbox:
    #    needs:
    #      - yaml-lint
    #      - json-lint
    #      - xml-lint
    #      - powershell-lint
    #      - shellcheck-lint
    #      - packer-iso-check
    #      - packer-lint
    uses: ./.github/workflows/packer-builds-virtualbox.yml
    secrets: inherit

  packer-builds-vmware:
    #    needs:
    #      - yaml-lint
    #      - json-lint
    #      - xml-lint
    #      - powershell-lint
    #      - shellcheck-lint
    #      - packer-iso-check
    #      - packer-lint
    uses: ./.github/workflows/packer-builds-vmware.yml
    secrets: inherit
#
#  check_jobs_pass:
#    if: always()
#    needs:
#      - markdown-lint
#      - yaml-lint
#      - json-lint
#      - xml-lint
#      - powershell-lint
#      - shellcheck-lint
#      # - packer-iso-check
#      # - packer-lint
#      # - packer-builds-amzlinux
#      # - packer-builds-hyperv
#      # - packer-builds-parallels
#      # - packer-builds-qemu
#      # - packer-builds-virtualbox
#      # - packer-builds-vmware
#    runs-on: Ubuntu-latest
#    steps:
#      - name: Decide whether the needed jobs succeeded or failed
#        uses: re-actors/alls-green@main
#        with:
#          allowed-failures:
#          allowed-skips: ${{ toJSON(needs) }}
#          jobs: ${{ toJSON(needs) }}
