---
on:
  workflow_call:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    container: ruby:alpine
    steps:
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Pull Change list
        id: changed-files
        uses: collin-miller/git-changesets@master
      - name: Verify Changed files
        id: verify-changed-files
        run: |
          echo '${{ steps.changed-files.outputs.added_modified }}' > changed.txt
          if grep ".*\.md" changed.txt; then
            echo "::set-output name=files_changed::true"
          else
            echo "::set-output name=files_changed::false"
          fi
      - name: Run Markdown Linter
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          gem install mdl
          find . -type f -iname "*.md" -exec mdl \{\} \+
