---
on:
  workflow_call:
    inputs:
      os_matrix:
        required: true
        type: string

permissions:
  contents: read

env:
  PACKER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  # PACKER_LOG: "1"

jobs:
  x86_64:
    runs-on: [self-hosted, X64, parallels]
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os_matrix) }}
        provider:
          - parallels-iso
    steps:
      - name: Checkout
        uses: actions/checkout@main
#      - name: Setup Packer
#        uses: hashicorp/setup-packer@main
#        with:
#          version: latest
      - name: Bento build
        run: |
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-x86_64.pkrvars.hcl"
          ls -alh builds/build_complete/
          cat builds/build_complete/${{ matrix.os }}*-x86_64._metadata.json
      - name: Bento Test
        run: |
          eval "$(chef shell-init bash)"
          bento test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-parallels-x86_64"
          path: |
            builds/testing_passed/x86_64/*.box
            builds/testing_passed/x86_64/*.json
          overwrite: true
          retention-days: 10
          compression-level: 0 # no compression
      - name: Remove VM in case of canceled job
        if: cancelled()
        run: |
          VM="$(prlctl list -a | grep ${{ matrix.os }} | cut -d " " -f 1)"
          echo "VM Name: $VM"
          echo Powering off and deleting any existing VMs named ${{ matrix.os }}*-amd64
          prlctl stop "$VM" --kill 2> /dev/null
          sleep 1
          prlctl delete "$VM" 2> /dev/null
          sleep 2
