---
on:
  workflow_call:

env:
  PACKER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  x86_64:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        os:
          - almalinux-9
        provider:
          - parallels-iso
          - virtualbox-iso
          - vmware-iso
          - qemu
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Virtualization Software
        run: |
          brew install qemu libvirt
          brew services start libvirt
          brew install --cask parallels parallels-virtualization-sdk virtualbox vmware-fusion vagrant vagrant-vmware-utility
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Install Bento
        run: |
          eval "$(chef shell-init bash)"
          gem build bento.gemspec
          gem install bento-*.gem
          df -h
      - name: Bento build
        run: |
          # rm -rf builds
          # sudo mkdir -p /mnt/builds/iso
          # sudo chmod -R 777 /mnt/builds
          # sudo ln -s /mnt/builds ./
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-x86_64.pkrvars.hcl"
          ls -alh builds/
          cat builds/${{ matrix.os }}*-x86_64._metadata.json

  aarch64:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - almalinux-9
        provider:
          - parallels-iso
          - vmware-iso
          - qemu
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Virtualization Software
        run: |
          brew install qemu libvirt
          brew services start libvirt
          brew install --cask parallels parallels-virtualization-sdk vmware-fusion vagrant vagrant-vmware-utility
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      - name: Install Bento
        run: |
          eval "$(chef shell-init bash)"
          gem build bento.gemspec
          gem install bento-*.gem
          df -h
      - name: Bento build
        run: |
          # rm -rf builds
          # sudo mkdir -p /mnt/builds/iso
          # sudo chmod -R 777 /mnt/builds
          # sudo ln -s /mnt/builds ./
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-aarch64.pkrvars.hcl"
          ls -alh builds/
          cat builds/${{ matrix.os }}*-aarch64._metadata.json
